apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: samanthagloria.me
spec:
  secretName: samanthagloria-me-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: samanthagloria.me
  dnsNames:
  - samanthagloria.me
  