apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: default
spec:
  selector:
    app: portfolio
  type: ClusterIP    
  ports:
  - protocol: TCP
    port: 4000 
    targetPort: 80
---  